<table cellpadding="0" cellspacing="5" align="center" style="margin-top:32px">
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <img src="/img/anshtayn.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/ahmatova.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/bob_marly.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/chanel.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/gagarin.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/dalay_lama.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/ekaterina.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/dali.jpg" width="83" height="83">
    </td>
  </tr>
  <tr>
    <td>
      <img src="/img/chaplin.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/marks.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/merkury.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/mizin.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/napoleon.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/pushkin.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/vertinsky.jpg" width="83" height="83">
    </td>
    <td>
      <img src="/img/monaliza.jpg" width="83" height="83">
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>