<table cellpadding="0" cellspacing="5" align="center" style="margin-top:32px">
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/anstayn.swf" width="83" height="83">
      <param name="movie" value="/img/anstayn.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/ahmatova.swf" width="83" height="83">
      <param name="movie" value="/img/ahmatova.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/bobmarly.swf" width="83" height="83">
      <param name="movie" value="/img/bobmarly.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/chanel.swf" width="83" height="83">
      <param name="movie" value="/img/chanel.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/gagarin.swf" width="83" height="83">
      <param name="movie" value="/img/gagarin.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/dalaylama.swf" width="83" height="83">
      <param name="movie" value="/img/dalaylama.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/ekaterina.swf" width="83" height="83">
      <param name="movie" value="/img/ekaterina.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/dali.swf" width="83" height="83">
      <param name="movie" value="/img/dali.swf" />
      </object>
    </td>
  </tr>
  <tr>
    <td>
      <object type="application/x-shockwave-flash" data="/img/chaplin.swf" width="83" height="83">
      <param name="movie" value="/img/chaplin.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/marks.swf" width="83" height="83">
      <param name="movie" value="/img/marks.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/merkury.swf" width="83" height="83">
      <param name="movie" value="/img/merkury.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/mizin.swf" width="83" height="83">
      <param name="movie" value="/img/mizin.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/napoleon.swf" width="83" height="83">
      <param name="movie" value="/img/napoleon.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/pushkin.swf" width="83" height="83">
      <param name="movie" value="/img/pushkin.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" data="/img/vertinsky.swf" width="83" height="83">
      <param name="movie" value="/img/vertinsky.swf" />
      </object>
    </td>
    <td>
      <object type="application/x-shockwave-flash" class="flash" data="/img/anstayn.swf" width="83" height="83">
      <param name="movie" value="/img/monaliza.swf" />
      </object>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>