version: '3.2'
services:

  kolesa-web-php53:
    build:
      context: ./web-php53
    container_name: ${SITE}-web-php53
    environment:
      - VIRTUAL_HOST
    volumes:
      - ${SITE_DIR}:/var/www/html
      - ${CMS_DIR}:/var/www/html/vendor/inetcms
    depends_on:
      - kolesa-mysql
    networks:
      static-network:
    restart: always

  kolesa-mysql:
    build:
      context: ./mysql
      args:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: 'aqq999'
        MYSQL_USER: 'aqq999'
        MYSQL_PASSWORD: 'password'
        DATABASE_DIR: ${DATABASE_DIR}
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=aqq999
        - MYSQL_USER=aqq999
        - MYSQL_PASSWORD=password
        - DATABASE_DIR
    container_name: ${SITE}-mysql
    networks:
      static-network:
    restart: always

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
